language: java
compiler:
  - gcc
  - clang
  
dist: xenial

arch:
  - amd64
  - ppc64le
  
jdk:
  - openjdk10

addons:
  apt:
    packages:
     - ant 1.10.7
     - maven
script:
    - jdk_switcher use openjdk10
    - ant build
    - cd maven2
    - mvn test
