language: java

compiler:
  - gcc
  - clang
  
dist: xenial

arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages:
     - ant 1.10.7
     - maven
script:
    - ant
    - cd maven2
    - mvn clean test
