language: java
compiler:
  - gcc
  - clang
  
dist: xenial

arch:
  - amd64
  - ppc64le

addons:
  apt:
    packages:
     - ant 1.10.7
     - maven
script:
    - ant build
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - mvn test
